# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 56a1cb9dd28ba337422214dd8c4570e04e7737b829478727ceb7c7c611b636d44f36cf8921940adbb792d42c075540d539bccb6364495eb89f9a4c4b9e271581

test:
  secret_key_base: d4c8f5414644ffbc084b674fb871f24498e4d5d3140163028125af9ba5729a02ce97a60c8e97f42434310a243bacd8a9f8076ab98c6438c6701ef344ec1cd1c3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
